import {useState} from 'react';import type {Product,Category,Brand} from '../../types/catalog';
interface Props{product:Product|null;categories:Category[];brands:Brand[]}
export default function ProductEditor({product,categories,brands}:Props){
const [gallery,setGallery]=useState<string[]>(product?.galeria||[]),[specs,setSpecs]=useState<[string,string][]>(Object.entries(product?.especificacoes||{})),[main,setMain]=useState(product?.imagem_principal||''),[busy,setBusy]=useState(false),[feedback,setFeedback]=useState('');
async function upload(file:File){setBusy(true);setFeedback('Enviando imagem…');try{const body=new FormData();body.set('file',file);const response=await fetch('/api/admin/upload',{method:'POST',body});const result=await response.json();if(!response.ok)throw new Error(result.error);if(!main)setMain(result.url);else setGallery(g=>[...g,result.url]);setFeedback('Imagem enviada. Salve o produto para confirmar.');}catch(e){setFeedback(e instanceof Error?e.message:'Falha no envio.');}finally{setBusy(false);}}
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setFeedback('');const form=new FormData(e.currentTarget);const body={...Object.fromEntries(form),categoria_id:form.get('categoria_id')||null,marca_id:form.get('marca_id')||null,ordem:Number(form.get('ordem')),ativo:form.get('ativo')==='on',destaque:form.get('destaque')==='on',imagem_principal:main,galeria:gallery.filter(Boolean),especificacoes:Object.fromEntries(specs.filter(([k])=>k.trim()))};
try{const response=await fetch('/api/admin/products/'+(product?.id||'novo'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error||'Não foi possível salvar.');window.location.assign('/admin/produtos');}catch(e){setFeedback(e instanceof Error?e.message:'Erro de conexão.');setBusy(false);}}
function move(index:number,delta:number){setGallery(g=>{const next=[...g];[next[index],next[index+delta]]=[next[index+delta],next[index]];return next;});}
return <form className="admin-form" onSubmit={submit}>
<label>Nome *<input name="nome" required minLength={2} maxLength={180} defaultValue={product?.nome}/></label>
<label>Slug *<input name="slug" required pattern="[a-z0-9]+(-[a-z0-9]+)*" maxLength={180} defaultValue={product?.slug}/><span className="help">Exemplo: bomba-para-piscina</span></label>
<label>Categoria *<select name="categoria_id" required defaultValue={product?.categoria_id||''}><option value="">Selecione</option>{categories.map(c=><option value={c.id} key={c.id}>{c.nome}{!c.ativo?' (inativa)':''}</option>)}</select></label>
<label>Marca<select name="marca_id" defaultValue={product?.marca_id||''}><option value="">Sem marca informada</option>{brands.map(b=><option value={b.id} key={b.id}>{b.nome}</option>)}</select></label>
<label>Código<input name="codigo" maxLength={80} defaultValue={product?.codigo}/></label><label>Ordem de exibição<input type="number" name="ordem" min="0" max="100000" defaultValue={product?.ordem||0}/></label>
<label className="full-width">Descrição curta<input name="descricao_curta" maxLength={300} defaultValue={product?.descricao_curta}/></label>
<label className="full-width">Descrição completa<textarea name="descricao" maxLength={20000} rows={6} defaultValue={product?.descricao}/></label>
<label className="checkbox"><input type="checkbox" name="ativo" defaultChecked={product?.ativo??false}/>Produto ativo no catálogo</label>
<label className="checkbox"><input type="checkbox" name="destaque" defaultChecked={product?.destaque??false}/>Destaque na página inicial</label>
<label className="full-width">Imagem principal (URL HTTPS)<input value={main} onChange={e=>setMain(e.target.value)} placeholder="https://…"/></label>
<label className="full-width">Enviar imagem (JPEG, PNG ou WebP, até 5 MB)<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{if(e.target.files?.[0])void upload(e.target.files[0]);e.target.value='';}}/></label>
<div className="full-width"><h2 style={{fontSize:22}}>Galeria de imagens</h2>{gallery.map((url,index)=><div className="image-editor-row" key={index}><input aria-label={'URL da imagem '+(index+1)} value={url} onChange={e=>setGallery(g=>g.map((v,i)=>i===index?e.target.value:v))}/><button type="button" className="editor-mini-button" disabled={index===0} onClick={()=>move(index,-1)} aria-label="Mover imagem para cima">↑</button><button type="button" className="editor-mini-button" disabled={index===gallery.length-1} onClick={()=>move(index,1)} aria-label="Mover imagem para baixo">↓</button><button type="button" className="editor-mini-button" onClick={()=>setGallery(g=>g.filter((_,i)=>i!==index))} aria-label="Remover imagem">×</button></div>)}<button type="button" className="editor-mini-button" disabled={gallery.length>=20} onClick={()=>setGallery(g=>[...g,''])}>Adicionar imagem por URL</button></div>
<div className="full-width"><h2 style={{fontSize:22}}>Especificações técnicas</h2>{specs.map(([key,value],index)=><div className="spec-editor-row" key={index}><input aria-label={'Nome da especificação '+(index+1)} placeholder="Ex.: Potência" value={key} maxLength={100} onChange={e=>setSpecs(s=>s.map((v,i)=>i===index?[e.target.value,v[1]]:v))}/><input aria-label={'Valor da especificação '+(index+1)} placeholder="Valor" value={value} maxLength={1000} onChange={e=>setSpecs(s=>s.map((v,i)=>i===index?[v[0],e.target.value]:v))}/><button className="editor-mini-button" type="button" onClick={()=>setSpecs(s=>s.filter((_,i)=>i!==index))} aria-label="Remover especificação">×</button></div>)}<button className="editor-mini-button" type="button" onClick={()=>setSpecs(s=>[...s,['','']])}>Adicionar especificação</button></div>
{feedback&&<p className="form-feedback full-width" role="status">{feedback}</p>}<button type="submit" className="button button-dark" disabled={busy}>{busy?'Aguarde…':'Salvar produto'}</button><a className="text-link" href="/admin/produtos">Voltar aos produtos</a>
</form>;
}

