import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowLeft, ArrowRight, Pause, Play, Waves } from 'lucide-react';
import {media,photo} from '../../config/media';
const slides=[
{video:'/video/hero-baby-diving.mp4',poster:'/video/hero-baby-diving-poster.jpg',label:'CUIDADO EM CADA GOTA',title:<>Tudo para uma<br/>piscina <em>perfeita.</em></>,text:'Produtos, equipamentos e soluções para manter sua piscina sempre limpa, segura e cristalina.',cta:'Conheça nossos produtos',href:'/produtos'},
{image:media.leisure,alt:'Piscina ao ar livre em um dia de verão',label:'MAIS LAZER. MAIS VIDA.',title:<>Mais tempo para<br/><em>aproveitar.</em></>,text:'A T&E Aqua Solutions ajuda você a cuidar da piscina para que sua preocupação seja apenas aproveitar.',cta:'Encontre a solução ideal',href:'/solucoes'},
{video:'/video/hero-swimmer.mp4',poster:'/video/hero-swimmer-poster.jpg',label:'CLAREZA QUE FAZ A DIFERENÇA',title:<>Água limpa começa<br/>com os produtos <em>certos.</em></>,text:'Produtos selecionados para tratamento, manutenção e cuidado completo da sua piscina.',cta:'Ver produtos',href:'/produtos?categoria=tratamento-da-agua'},
{image:media.pool,alt:'Piscina com sistema de circulação de água',label:'DO PROJETO AO PRÓXIMO MERGULHO',title:<>Soluções para quem<br/>entende de <em>piscina.</em></>,text:'Equipamentos, acessórios e materiais para residências, profissionais e empresas do setor.',cta:'Conheça a T&E Aqua',href:'/empresa'},
];
export default function Hero(){
const [active,setActive]=useState(0),[paused,setPaused]=useState(false),[hover,setHover]=useState(false),[focused,setFocused]=useState(false),[reduced,setReduced]=useState(true),[visible,setVisible]=useState(true);
const touch=useRef<number|null>(null); const root=useRef<HTMLElement>(null); const heroVideo0=useRef<HTMLVideoElement>(null); const heroVideo2=useRef<HTMLVideoElement>(null);
useEffect(()=>{const mq=window.matchMedia('(prefers-reduced-motion: reduce)');setReduced(mq.matches);const change=()=>setReduced(mq.matches);mq.addEventListener('change',change);const visibility=()=>setVisible(!document.hidden);document.addEventListener('visibilitychange',visibility);const observer=new IntersectionObserver(([entry])=>setVisible(entry.isIntersecting&&!document.hidden));if(root.current)observer.observe(root.current);return()=>{mq.removeEventListener('change',change);document.removeEventListener('visibilitychange',visibility);observer.disconnect();};},[]);
useEffect(()=>{const sync=(v:HTMLVideoElement|null,index:number)=>{if(!v)return;if(active===index&&!reduced&&visible){const source=v.querySelector<HTMLSourceElement>('source[data-src]');if(source){source.src=source.dataset.src!;source.removeAttribute('data-src');v.load();}v.play().catch(()=>{});}else v.pause();};sync(heroVideo0.current,0);sync(heroVideo2.current,2);},[active,reduced,visible]);
useEffect(()=>{if(paused||hover||focused||reduced||!visible)return;const timer=window.setInterval(()=>setActive(a=>(a+1)%slides.length),7000);return()=>window.clearInterval(timer);},[paused,hover,focused,reduced,visible,active]);
const move=(n:number)=>setActive(a=>(a+n+slides.length)%slides.length);
return <section ref={root} className="hero" aria-label="Soluções para sua piscina" aria-roledescription="carrossel" onMouseEnter={()=>setHover(true)} onMouseLeave={()=>setHover(false)} onFocusCapture={()=>setFocused(true)} onBlurCapture={e=>{if(!e.currentTarget.contains(e.relatedTarget))setFocused(false);}} onTouchStart={e=>touch.current=e.touches[0].clientX} onTouchEnd={e=>{if(touch.current!==null){const delta=touch.current-e.changedTouches[0].clientX;if(Math.abs(delta)>60)move(delta>0?1:-1);touch.current=null;}}}>
{slides.map((s,i)=><div key={i} className={'hero-slide '+(active===i?'active':'')} aria-hidden={active!==i} inert={active!==i}>
{i===0?<video ref={heroVideo0} className="hero-photo" poster={s.poster!} width="1280" height="720" muted loop playsInline autoPlay={!reduced} preload="auto" aria-hidden="true"><source src={s.video!} type="video/mp4"/></video>:i===2?<video ref={heroVideo2} className="hero-photo" poster={s.poster!} width="1280" height="720" muted loop playsInline preload="none" aria-hidden="true"><source data-src={s.video!} type="video/mp4"/></video>:<img className="hero-photo" src={photo(s.image!,1920)} srcSet={[640,960,1440,1920].map(w=>photo(s.image!,w)+' '+w+'w').join(', ')} sizes="100vw" width="1920" height="1280" alt={s.alt!} fetchPriority="low" loading="lazy" decoding="async"/>}
<div className="hero-shade"/><div className="container hero-content"><p className="hero-eyebrow"><span/> {s.label}</p>{i===0?<h1>{s.title}</h1>:<h2>{s.title}</h2>}<p className="hero-description">{s.text}</p><div className="hero-actions"><a className="button" href={s.href}>{s.cta}<ArrowUpRight size={19}/></a><a className="hero-secondary" href="/contato">Fale conosco <ArrowUpRight size={18}/></a></div></div>
</div>)}
<div className="container hero-bottom"><div className="hero-pagination"><span className="slide-number">0{active+1}<span> / 04</span></span><div className="slide-dots">{slides.map((_,i)=><button key={i} aria-label={'Ir para o slide '+(i+1)} aria-current={i===active?'true':undefined} onClick={()=>setActive(i)} className={i===active?'active':''}/>)}</div><button className="hero-control play-control" onClick={()=>setPaused(p=>!p)} aria-label={paused?'Reproduzir slides':'Pausar slides'} aria-pressed={paused}>{paused?<Play size={15}/>:<Pause size={15}/>}</button></div><div className="hero-signature"><Waves size={26}/><span>Água boa.<br/><strong>Vida leve.</strong></span></div><div className="hero-arrows"><button className="hero-control" aria-label="Slide anterior" onClick={()=>move(-1)}><ArrowLeft size={20}/></button><button className="hero-control" aria-label="Próximo slide" onClick={()=>move(1)}><ArrowRight size={20}/></button></div></div>
<span className="sr-only" aria-live={paused||focused?'polite':'off'}>Slide {active+1} de 4</span>
</section>;
}

